allowBuilds:
  argon2: true
  esbuild@0.25.12: true
  esbuild@0.28.1: true

minimumReleaseAge: 0

overrides:
  'drizzle-kit@0.31.10>@esbuild-kit/esm-loader': '-'
  'postcss@<=8.5.22': 8.5.25

verifyDepsBeforeRun: false
